@startuml
'https://plantuml.com/sequence-diagram

Main  *-- "2..6" BankAccount : has
Main "1" *-- UI : has
Player *-- "1" BankAccount : has a
Field <|-- Consequence
Field <|-- Property
Main *-- Board : has a
Consequence <|-- Tax
Consequence <|-- Chance
Consequence <|-- Start
Consequence <|-- Prison
Consequence <|-- Visit
Consequence <|-- Bonus
Property <|-- Plot
Property <|-- Business
Business <|-- ShippingLine
Business <|-- Brewery


Player : - int id
Player : - int counter
Player : - String name
Player : - int position
Player : - BankAccount account
Player : + handleMoney()
Player : + updatePosition()
Player : + String toString();

BankAccount : - int balance
BankAccount : - String Owner
BankAccount : - int stalkingCounter
BankAccount : + void doTransaction()
BankAccount : + String toString ()
BankAccount : + String getOwner()
BankAccount : + int getBalance()

UI : + void createAccount()
UI : + void manageAccounts()
UI : + String getUserInput()

Main : + static ArrayList<BankAccount>
Main : + static int MAX
Main : + static readGameData()
Main : + static printAccounts()
Main : + static showMenu()
Main : + static saveGameData()

Field : - String label
Field : - int id
Field : - int cost
Field : - int income
Field : + String createOption()
Field : + void processResponse()

Consequence : + onAccept()
Consequence : + onReject()
Consequence : + String toString()

Property : seriesID
Property : + onAccept()
Property : + onReject()
Property : + String toString()

Board : - Field[] fields
Board : Dice dice
Board : - setFields()



@enduml