@startuml
'https://plantuml.com/sequence-diagram

Main "1" *-- "6" BankAccount : has
Main "1" *-- UI : has

BankAccount : Float balance
BankAccount : String Owner
BankAccount : int stalkingCounter
BankAccount : void doTransaction()
BankAccount : String toString ()
BankAccount : String getOwner()
BankAccount : float getBalance()

UI : void createAccount()
UI : void manageAccounts()
UI : String getUserInput()

Main : static ArrayList<BankAccount>
Main : static int MAX
Main : static readGameData()
Main : static printAccounts()
Main : static showMenu()
Main : static saveGameData()

@enduml