@startuml
'https://plantuml.com/use-case-diagram


actor user as u

  usecase "StartGame" as UCA1
  usecase "RegisterPlayers" as UCA2

  usecase "TakeTurn" as UC1
  usecase "LandOnField" as UC2
  usecase "LandOnOrPassStartField" as UC3
  usecase "LandOnProperty" as UC4
  usecase "LandOnConsequence" as UC5
  usecase "HandleMoney" as UC6
 usecase "QuitGame" as UC7
 usecase "MakeChoice" as UC8

u --> (UCA1)
(UCA1) --> (UC1) : No savegame
(UCA1) --> (UCA2) : check for savegame
(UCA2) --> (UC1) : Proceeds
(UC1) --> (UC2) : proceeds
(UC2) --> (UC4) : proceeds
(UC2) --> (UC5) : proceeds
(UC2) --> (UC3) : proceeds
(UC4) --> (UC8) : proceeds
(UC5) --> (UC8) : proceeds
(UC8) --> (UC6) : proceeds
(UC8) --> (UC1) : proceeds
(UC1) --> (UC7) : proceeds
@enduml

left to right direction