@startuml
abstract Tournament
object UI

Controller *-- Tournament
Tournament *-- Team
KnockOutTournament *-- Bracket
Bracket *-- Match
Group *-- Match
Team *-- MatchHistory
Match *-- Team
Team *-- Player
MatchHistory *-- Match
GroupTournament *-- Group
Tournament *-- BracketView
Tournament <|-- KnockOutTournament
Tournament <|-- GroupTournament

UI : + showMenu(Controller)

Controller : - ArrayList<Tournament> tournaments
Controller : + void createTournament()
Controller : + void deleteTournament()
Controller : + void saveTournament()
Controller : + void postTournament()

Tournament : - Team winner
Tournament : - String name
Tournament : - ArrayList<Team> teams
Tournament : - String startDate
Tournament : - boolean isFixedDuration
Tournament : + void readTeamsFromFile()
Tournament : + void createTeam()

KnockOutTournament : - Bracket bracket
KnockOutTournament : + void createBracket()
KnockOutTournament : + void runBracket()
GroupTournament : - ArrayList<Group> groups

Group : - String name
Group : - int amountOfMatches
Group : - ArrayList<Team> teams
Group : - Team[] ranking
Group : - Match matches

Bracket : - Match[] finals
Bracket : - Match[] semiFinal
Bracket : - Match[] quarterFinal
Bracket : - Match[] preliminaryFinal
Bracket : + void processBracket()
Bracket : + Team processFinal()
Bracket : + void processSemiFinal()
Bracket : + void processQuarterFinal(Team[])
Bracket : + void processPreliminaryFinal()
Bracket : + void createFinal(Team[])
Bracket : + void createSemiFinal(Team[])
Bracket : + void createQuarterFinal(Team[])
Bracket : + void createPreliminaryFinal(ArrayList<Team>)
Bracket : + announceMatches(Match[])
Bracket : + announceBracketStages(String)
Bracket : + announceBracket(Match[])
Bracket : + ArrayList<(Match[]> exportBracketToView()
Bracket : + void displayBracket()

BracketView : - String[] teamNames
BracketView : + void loadTeamsIntoView(ArrayList<(Match[])
BracketView : + showBracketView()

MatchHistory : - ArrayList<Match> matches
MatchHistory : + @Override String toString()

Match : - Team[] teams
Match : - Team winner
Match : - String startTime
Match : - int TeamAScore
Match : - int TeamBScore
Match : - int matchDuration
Match : + void processMatch()
Match : + addGoalScore()
Match : + @Override String toString()

Team : - String name
Team : - ArrayList<Player> players
Team : - MatchHistory matchHistory
Team : - int goalScore
Team : - int points
Team : + void addPlayer()
Team : + void removePlayer()
Team : + void joinTournament()
Team : + void forfeitTournament()
Team : + @Override String toString()

Player : - String name
Player : - int age
Player : - char gender
@enduml