@startuml
'https://plantuml.com/class-diagram

Main *-- Controller
ComputeVAT <|-- Controller
Controller *-- View
Controller *-- CalculateVat
Controller *-- Dialog

Main : + static void main(String[] args)

Controller : + runController()

View : - String CURRENCY
View : - String MSG
View : + doView(double Result, String typeOfResult)

CalculateVat : - PRCVAT
CalculateVat : + doVAT(double number)

Dialog : + doDiag()

ComputeVAT : # final int PRCVAT
ComputeVAT : # final String MSG
ComputeVAT : # final String CURRENCY

@enduml